paths:
     - '%HOMEDRIVE%\temp'
     - '%HOMEDRIVE%\Users'
     - '%HOMEDRIVE%\ProgramData'
     - '%SYSTEMROOT%'
names:
     - 'nmap'
     - 'wireshark'
     - 'sqlmap'
     - 'nikto'
     - 'openvas'
     - 'spiderfoot'
     - 'Invoke-Obfuscation'
     - 'bloodhound'
     - 'mimikatz'
     - 'paexec'
     - 'crackmapexec'
     - 'lazagne'
     - 'empire'
     - 'pupy'
     - 'powershell-rat'
     - 'rubeus'
     - 'sharpup'
     - 'sharpgpoabuse'
     - 'seatbelt'
     - 'powerup'
     - 'safetykatz'
     - 'keethief'
     - 'forgecert'
     - 'lockless'
     - 'sharpwmi'
     - 'wmiexec'
     - 'sharpdump'
     - 'kekeo'
     - 'curveball'
     - 'xconsole'
     - 'PrintNightmareLPE'
     - 'starterO'
     - 'starterOF'
     - 'runsysO'
     - 'runsysOF'
     - 'cve-2021-1732_exploit'
     - 'cve-2019-1458'
     - 'InstallerFileTakeOver'
     - 'Recon-AD'
     - 'PSPKIAudit'
     - 'Grouper'
     - 'ImproHound'
     - 'ADRecon'
     - 'ADCSPwn'
     - 'Dumpert'
     - 'CredBandit'
     - 'CloneVault'
     - 'SharpLAPS'
     - 'foratz'
     - 'PPLKiller'
     - 'AndrewSpecial'
     - 'Chlonium'
     - 'SharpCloud'
     - 'pypykatz'
     - 'nanodump'
     - 'watson'
     - 'peass'
     - 'dazzleup'
     - 'sweetpotato'
     - 'multipotato'
     - 'edrsandblast'
     - 'backstab'
     - 'phant0m'
     - 'blocketw'
     - 'sharpstay'
     - 'sharpersist'
     - 'sharphide'
     - 'doucme'
     - 'iis-raid'
     - 'sharpyshell'
     - 'liquid snake'
     - 'powerupsql'
     - 'sharprdp'
     - 'movekit'
     - 'sharpnopsexec'
     - 'impacket'
     - 'cimplant'
     - 'powerlessshell'
     - 'kerbrute'
     - 'mssqlproxy'
     - 'inveigh'
     - 'inveighzero'
     - 'sharpspray'
     - 'sharpallowedtoact'
     - 'sharprdphijack'
     - 'cheesetools'
     - 'cheesedcom'
     - 'cheeseps'
     - 'cheeseexec'
     - 'cheeserdp'
     - 'cheesesql'
     - 'hook_finder64'
     - 'hook_finder_64'
     - 'hook_finder32'
     - 'hook_finder'
     - 'listdll'
     - 'byebyedll-debug-poc'
     - 'byebyedll'
     - 'getsyscall'
     - 'Invoke-GoFetch'
     - 'Invoke-Mimikatz'
     - 'Invoke-PsExec'
     - 'sharphound'
     - 'responder'
     - 'SessionGopher'
     - 'powersploit'
     - 'nishang'
     - 'wmiops'
     - 'mimipenguin'
     - 'psexec'
     - 'icebreaker'
     - 'wsuspendu'
     - 'netripper'
     - 'lethalhta'
     - 'Invoke-PowerThief'
     - 'snarf_client'
     - 'redsnarf'
     - 'Invoke-honeypotbuster'
     - 'powerview'
     - 'get-gpppassword'
     - 'invoke-aclpwn'
     - 'ms14-068'
     - 'adaclscan'
     - 'aclight'
     - 'aclight2'
     - 'LAPSToolkit'
     - 'pingcastle'
     - 'riskyspns'
     - 'Find-PotentiallyCrackableAccounts'
     - 'cve-2017-0213'
     - 'cve-2017-0213_x64'
     - 'x64'
     - 'x86'
     - 'ms03-026'
     - 'ms05-039'
     - 'ms08-025'
     - 'ms08-067'
     - 'smbrelay3'
     - 'ms10-059'
     - 'ms17-017'
     - '41015'
     - '40429'
     - 'bfill'
     - 'potato'
     - 'ms16-032'
     - 'bsod'
     - 'elevator'
     - 'trebuchet'
     - '37049-32'
     - 'talihou32'
     - 'talihou64'
     - 'uacme'
     - 'sherlock'
     - 'Invoke-EnvBypass'
     - 'Invoke-EventVwrBypass'
     - 'Invoke-MS16032'
     - 'Invoke-WScriptBypassUAC'
     - 'tokenvator'
     - 'pykek'
     - 'adaclscanner'
