---
paths:
   - '%HOMEDRIVE%\temp'
   - '%HOMEDRIVE%\Users'
   - '%HOMEDRIVE%\ProgramData'
   - '%SYSTEMROOT%\System32'
   - '%SYSTEMROOT%\Syswow64'
extensions:
   # Executable-type Files often used by malware
   - '.hta'
   - '.js'  #Many False Positives in most installations.
   - '.vbs'
   - '.vba'
   - '.ps1'
   - '.ps'
   - '.psm1'
   - '.exe'
   - '.bat'
   - '.docx'
   - '.xlsx'
   - '.xlsm'
   - '.docm'
   - '.doc'
   - '.xls'
   - '.ppt'
   - '.pptm'
   - '.potm'
   - '.ppam'
   - '.ppsm'
   - '.sldm'
   - '.dotm'
   - '.xltm'
   - '.xlam'
   - '.vb'
   - '.pdf'
   - '.jar'
   #- '.tmp'
   #- '.inf'
   - '.msi'
   - '.msp'
   - '.gadget'
   - '.ps1xml'
   - '.ps2'
   - '.ps2xml'
   - '.psc1'
   - '.psc2'
   - '.py'
   - '.cmd'
   - '.com'
   - '.vbe'
   - '.jse'
   - '.jsp'
   - '.scr'
   - '.zip'
   - '.rar'
   - '.gz'
   - '.iso'
   - '.img'
   - '.msp'
   - '.cpl'
   - '.ws'
   - '.wsf'
   - '.wsh'
   - '.wsc'
   - '.msh1'
   - '.msh'
   - '.msh2'
   - '.mshxml'
   - '.msh1xml'
   - '.msh2xml'
   - '.lnk'
   - '.scf'
   -
   # Ransomware Extensions
   - '.micro'
   - '.aaa'
   - '.crjoker'
   - '.cryptorlocker'
   - '.ecc'
   - '.encrypted'
   - '.exx'
   - '.ezz'
   - '.xyz'
   - '.zzz'
   - '.frtrss'
   - '.locky'
   - '.lol!'
   - '.lol'
   - '.r5a'
   - '.ttt'
   - '.vault'
   - '.vvv'
   - '.xxx'
   - '.crypt'
   - '.RSA'
   - '.CTBL'
   - '.CTBL2'
   - '.crjocker'
   - '.locked'
   - '.HA3'
   - '.0x0'
   - '.bleep'
   - '.magic'
   - '.enc'
   - '.vscrypt'
   - '.rrk'
   - '.rdm'
   - '.infected'
   - '.korrektor'
   - '.bloc'
   - '.sanctioned'
   - '.pzdc'
   - '.good'
   - '.supercrypt'
   - '.ccc'
   - '.R16M01D05'
   - '.xrtn'
   - '.zepto'
   - '.cerber'
   - '.cerber3'
   - '.cryp1'
   - '.mole'
   - '.onion'
   - '.axx'
   - '.osiris'
   - '.crypz'
   - '.cerber2'
   - '.sage'
   - '.globe'
   - '.exx'
   - '.good'
   - '.wallet'
   - '.1txt'
   - '.decrypt2017'
   - '.zzzzz'
   - '.MERRY'
   - '.enciphered'
   - '.aesir'
   - '.r5a'
   - '.enigma'
   - '.cryptowall'
   - '.loli'
   - '.breakingbad'
   - '.dharma'
   - '.coded'
   - '.ha3'
   - '.damage'
   - '.wcry'
   - '.lol!'
   - '.mrcr1'
   - '.sexy'
   - '.crjoker'
   - '.fantom'
   - '.rrk'
   - '.legion'
   - '.kratos'
   - '.lechiffre'
   - '.zcrypt'
   - '.maya'
   - '.file0locked'
   - '.crinf'
   - '.serp'
   - '.potato'
   - '.ytbl'
   - '.surprise'
   - '.angelamerkel'
   - '.windows10'
   - '.lesli'
   - '.serpent'
   - '.pegs1'
   - '.dale'
   - '.xyz'
   - '.pdcr'
   - '.1cbu1'
   - '.venusf'
   - '.coverton'
   - '.thor'
   - '.rnsmwr'
   - '.evillock'
   - '.r16m01d05'
   - '.wflx'
   - '.nuclear55'
   - '.darkness'
   - '.rekt'
   - '.kernel_time'
   - '.zyklon'
   - '.dexter'
   - '.locklock'
   - '.cry'
   - '.vforvendetta'
   - '.btc'
   - '.raid10'
   - '.dcrypt'
   - '.zorro'
   - '.angleware'
   - '.purge'
   - '.shit'
   - '.atlas'
   - '.exotic'
   - '.crypted'
   - '.padcrypt'
   - '.hush'
   - '.vbransom'
   - '.rmcm1'
   - '.cryeye'
   - '.unavailable'
   - '.braincrypt'
   - '.crypte'
   - '._airacropencrypted'
   - '.stn'
   - '.paym'
   - '.spora'
   - '.rare1'
   - '.alcatraz'
   - '.pzdc'
   - '.ttt'
   - '.odcodc'
   - '.pays'
   - '.comrade'
   - '.antihacker2017'
   - '.herbst'
   - '.szf'
   - '.bript'
   - '.vindows'
   - '.barrax'
   - '.helpmeencedfiles'
   - '.hnumkhotep'
   - '.kyra'
   - '.fun'
   - '.bitstak'
   - '.payrms'
   - '.paymst'
   - '.payms'
   - '.kostya'
   - '.lovewindows'
   - '.madebyadam'
   - '.gefickt'
   - '.ifuckedyou'
   - '.oops'
   - '.conficker'
   - '.whereisyourfiles'
   - '.razy'
   - '.crab'
   - '.pubg'
   - '.vxlock'
allowlist:
   - '%SYSTEMROOT%\WinSxS\'
   - '%SYSTEMROOT%\SysWOW64\WindowsPowerShell'
   - '%SYSTEMROOT%\System32\WindowsPowerShell'
   - '%SYSTEMROOT%\System32\wbem'
   - '%SYSTEMROOT%\System32\WinBioPlugIns'
   - '%SYSTEMROOT%\System32\UNP'
   - '%SYSTEMROOT%\System32\DriverStore\FileRepository'
   - '%SYSTEMROOT%\System32\DRVSTORE'
   - '%SYSTEMROOT%\servicing\LCU'
   - '%SYSTEMROOT%\SystemApps\'
   - '%SYSTEMROOT%\Microsoft.NET\Framework64'
   - '%SYSTEMROOT%\Installer'
   - '%SYSTEMROOT%\SysWOW64\ras'
   - '%SYSTEMROOT%\SysWOW64\IME'
   - '%SYSTEMROOT%\Microsoft.NET\Framework'
   - '%SYSTEMROOT%\SysWOW64\Printing_Admin_Scripts'
   - '%SYSTEMROOT%\INF'
   - '%SYSTEMROOT%\diagnostics'
   - '%SYSTEMROOT%\assembly'
   - '%PROGRAMDATA%\Package Cache'
   - '%PROGRAMDATA%\chocolatey'
   - '%PROGRAMDATA%\Microsoft\VisualStudio'
...